"""
This is a setup.py script generated by py2applet

Usage:
    python setup_py2app.py py2app
"""

import os
import datetime
from setuptools import setup

APP = ['Macast.py']
DATA_FILES = ['i18n']
VERSION = "0.0.0"
with open('macast/.version', 'r') as f:
    VERSION = f.read().strip()
copyright = 'Copyright {} xfangfang and the Macast contributors.'.format(datetime.datetime.now().year)
OPTIONS = {
    'plist': {
        'LSUIElement': True,
        'NSHighResolutionCapable': True,
        'LSMinimumSystemVersion': '15.0',
        'CFBundleIdentifier': 'cn.xfangfang.Macast',
        'NSHumanReadableCopyright': copyright,
        'CFBundleShortVersionString': str(VERSION),
        'CFBundleVersion': str(VERSION),
        'NSSupportsAutomaticTermination': False,
        'NSAppleEventsUsageDescription': 'Macast needs Apple Events to communicate with system components.',
        # 支持 Apple Silicon 原生运行
        'LSArchitecturePriority': ['arm64', 'x86_64'],
    },
    'excludes': ['PIL', 'tkinter'],
    'packages': ['rumps', 'macast', 'macast_renderer'],
    'iconfile': os.path.abspath('macast/assets/icon.icns')
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    py_modules=[]
)
