# Copyright (c) 2021 by xfangfang. All Rights Reserved.


name: Build Macast

on:
  push:
    branches:
      - dev_test
      - morelog
  pull_request:
  workflow_dispatch:
    inputs:
      ssh_darwin:
        description: 'SSH connection to Darwin'
        required: false
        default: 'false'
      release:
        description: 'Push a new release'
        required: false
        default: 'false'

jobs:
  release:
    needs: [ build-darwin ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4

      - name: Version
        run: |
          ls -R
          export VERSION=`cat macast/.version`
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
          echo "DIST_DMG=Macast-MacOS-arm64-v${VERSION}.dmg" >> $GITHUB_ENV
          echo $GITHUB_ENV

      - name: Upload
        if: github.event.inputs.release == 'true' && github.event.inputs.release  != 'false' && !cancelled()
        uses: ncipollo/release-action@v1
        with:
          name: Macast ${{ env.VERSION }}
          tag: ${{ env.VERSION }}
          omitBodyDuringUpdate: true
          body: This release is built by github-action.
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          artifacts: ${{ env.DIST_DMG }}/${{ env.DIST_DMG }}

  build-darwin:
    runs-on: macos-26-arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install create-dmg
        run: brew install create-dmg

      - name: Install Requirement
        run: |
          pip3 install -r requirements/darwin.txt
          pip3 install py2app
          wget https://laboratory.stolendata.net/~djinn/mpv_osx/mpv-latest.tar.gz
          mkdir -p bin && tar --strip-components 2 -C bin -xzvf mpv-latest.tar.gz mpv.app/Contents/MacOS

      - name: Build
        id: compile
        run: |
          for file in i18n/*; do msgfmt -o $file/LC_MESSAGES/macast.mo $file/LC_MESSAGES/macast.po;echo $file;done
          python3 setup_py2app.py py2app --arch=arm64
          cp -R bin dist/Macast.app/Contents/Resources/
          export VERSION=`cat macast/.version`
          echo "DIST_DMG=Macast-MacOS-arm64-v${VERSION}.dmg" >> $GITHUB_ENV
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
          create-dmg --window-pos 200 120 --window-size 800 400 --icon-size 100 --icon "Macast.app" 200 190  --hide-extension "Macast.app" --app-drop-link 600 185  --volname "Macast-v${VERSION}-arm64 Installer" Macast-MacOS-arm64-v${VERSION}.dmg "dist/"
          echo "status=success" >> $GITHUB_OUTPUT

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh_darwin == 'true' && github.event.inputs.ssh_darwin  != 'false') || contains(github.event.action, 'ssh_darwin')
        env:
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

      - name: Upload dist
        uses: actions/upload-artifact@v4
        if: steps.compile.outputs.status == 'success'
        with:
          name: ${{ env.DIST_DMG }}
          path: ${{ env.DIST_DMG }}
